//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopbd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myshopdbEntities : DbContext
    {
        public myshopdbEntities()
            : base("name=myshopdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblcat> tblcats { get; set; }
        public DbSet<tblimage> tblimages { get; set; }
        public DbSet<tblorderdetail> tblorderdetails { get; set; }
        public DbSet<tblorder> tblorders { get; set; }
        public DbSet<tblpro> tblproes { get; set; }
        public DbSet<tbluser> tblusers { get; set; }
    }
}
