//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopbd
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcat
    {
        public tblcat()
        {
            this.tblproes = new HashSet<tblpro>();
        }
    
        public int cid { get; set; }
        public string cname { get; set; }
    
        public virtual ICollection<tblpro> tblproes { get; set; }
    }
}
