//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shopbd
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpro
    {
        public tblpro()
        {
            this.tblimages = new HashSet<tblimage>();
            this.tblorderdetails = new HashSet<tblorderdetail>();
        }
    
        public int pid { get; set; }
        public string pname { get; set; }
        public int pprice { get; set; }
        public string pdetails { get; set; }
        public int cid { get; set; }
    
        public virtual tblcat tblcat { get; set; }
        public virtual ICollection<tblimage> tblimages { get; set; }
        public virtual ICollection<tblorderdetail> tblorderdetails { get; set; }
    }
}
